---
- name: Install packages
  apt:
    state: latest
    name:
      - pyosmium
      - osmium-tool
      - curl
      - rsync

- name: Create data directory
  file:
    path: "{{ tilemaker_work_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest="{{ tilemaker_work_dir }}"
  with_items:
    - build-mbtiles
    - config-openmaptiles.json
  notify: Restart tilemaker

- name: Install Lua script
  template:
    src: "{{ item }}"
    dest: "{{ tilemaker_work_dir }}"
  with_items:
    - process-openmaptiles.lua
  notify: Restart tilemaker
  when: tilemaker_custom_lua_file is not defined

- name: Install custom Lua script
  ansible.builtin.copy:
    src: "{{ tilemaker_custom_lua_file }}"
    dest: "{{ tilemaker_work_dir }}process-openmaptiles.lua"
  notify: Restart tilemaker
  when: tilemaker_custom_lua_file is defined

- name: Copy area.geojson
  template:
    src: tilemaker/area.geojson
    dest: "{{ tilemaker_work_dir }}"
  notify: Restart tilemaker
  when: tilemaker_create_extract

- name: Make script executable
  file:
    dest: "{{ tilemaker_work_dir}}build-mbtiles"
    mode: "a+x"

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - tilemaker.service
    - tilemaker.timer
    - tilemaker-cleanup.service
    - tilemaker-cleanup.timer

- name: Start tilemaker.timer
  systemd:
    name: tilemaker.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Start tilemaker-cleanup.timer
  systemd:
    name: tilemaker-cleanup.timer
    state: started
    enabled: yes
    daemon_reload: yes
  when: tilemaker_cleanup 
