---
tilemaker_image: "ghcr.io/leonardehrenfried/tilemaker:2026-09-30T11-59"
tilemaker_start_time: 04:15:00
tilemaker_pbf_download_url: http://download.geofabrik.de/europe/germany-latest.osm.pbf
tilemaker_work_dir: "/var/tilemaker/"
tilemaker_create_extract: true
tilemaker_renumber: false
tilemaker_check_referential_integrity: false
# https://boundingbox.klokantech.com/ -> CSV
tilemaker_bounding_box: "-2.81,41.91,23.52,59.81"
# instead of keeping everything in RAM, put some intermediate data structure on disk
tilemaker_use_store: false
# should there be a notfication when tilemaker starts
tilemaker_notify_start: false
# deletes all pbf files in /var/tilemaker on the first Saturday of the month,
# to prevent corrupted pbf files from using pyosmium-up-to-date
tilemaker_cleanup: false

tileserver_restart_on_tilemaker_termination: false
